# Generated by Django 5.1.3 on 2024-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('artist_Image', models.ImageField(upload_to='Artist_Image/')),
                ('Music_Title', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=30)),
            ],
        ),
    ]
