# Generated by Django 5.1.3 on 2024-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_login_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_music',
            name='colaborators',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
