# Generated by Django 5.1.3 on 2024-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_post_music_colaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_music',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Music_Background/'),
        ),
    ]
