# Generated by Django 5.1.3 on 2024-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_post_music_cover_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_music',
            name='artist_Image',
        ),
        migrations.RemoveField(
            model_name='post_music',
            name='colaborators',
        ),
        migrations.AddField(
            model_name='post_music',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
