# Generated by Django 5.1.3 on 2024-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_remove_post_music_artist_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spicalkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('loginKey', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post_music',
            name='music',
        ),
    ]
