# Generated by Django 5.1.3 on 2024-12-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_spicalkey_remove_post_music_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_music',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
